version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/server
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
    timeout: 300
    runas: ec2-user
    AfterInstall:
      - location: codedeploy/AfterInstall.sh
      timeout: 300
      runas: ec2-user
    ApplicationStart:
      - location: codedeploy/ApplicationStart.sh
      timeout: 20
      runas: ec2-user
    ValidateService:
      - location: codedeploy/ValidateService.sh
      timeout: 40
      runas: ec2-user
    ApplicationStop:
      - location: codedeploy/ApplicationStop.sh
      timeout: 20
      runas: ec2-user

